<a href="https://colab.research.google.com/github/Vignesh424/Pokemon-DataScience/blob/main/Decision_Tree_Pokemon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [437]:
#import libraries
import numpy as np
import pandas as pd

In [438]:
data=pd.read_csv('/content/pokedex_(Update_05.20).csv')

In [439]:
data.head()

Unnamed: 0  pokedex_number  ... against_steel against_fairy
0           0               1  ...           1.0           0.5
1           1               2  ...           1.0           0.5
2           2               3  ...           1.0           0.5
3           3               3  ...           1.0           0.5
4           4               4  ...           0.5           0.5

[5 rows x 51 columns]

In [440]:
data.isnull().sum()
data.isnull().any()

Unnamed: 0          False
pokedex_number      False
name                False
german_name          True
japanese_name        True
generation          False
status              False
species             False
type_number         False
type_1              False
type_2               True
height_m            False
weight_kg            True
abilities_number    False
ability_1            True
ability_2            True
ability_hidden       True
total_points        False
hp                  False
attack              False
defense             False
sp_attack           False
sp_defense          False
speed               False
catch_rate           True
base_friendship      True
base_experience      True
growth_rate          True
egg_type_number     False
egg_type_1           True
egg_type_2           True
percentage_male      True
egg_cycles           True
against_normal      False
against_fire        False
against_water       False
against_electric    False
against_grass       False
against_ice 

In [441]:
data.index

RangeIndex(start=0, stop=1028, step=1)

In [442]:
data = data.fillna(method='ffill')

In [443]:
x1=data.drop("Unnamed: 0" ,axis=1)

In [444]:
x1.head()

pokedex_number           name  ... against_steel against_fairy
0               1      Bulbasaur  ...           1.0           0.5
1               2        Ivysaur  ...           1.0           0.5
2               3       Venusaur  ...           1.0           0.5
3               3  Mega Venusaur  ...           1.0           0.5
4               4     Charmander  ...           0.5           0.5

[5 rows x 50 columns]

In [445]:
x=x1.drop(columns=['pokedex_number', 'german_name', 'abilities_number','height_m', 'weight_kg', 
                   'growth_rate','japanese_name', 'base_friendship', 'catch_rate','egg_type_number', 'ability_1',
                   'ability_2',  'ability_hidden','egg_type_1', 'egg_type_2', 'percentage_male','egg_cycles' ,
                   'against_normal', 'against_fire', 'against_water', 'against_electric', 'against_grass',
                   'against_ice', 'against_fight', 'against_poison', 'against_ground', 'against_flying',
                   'against_psychic', 'against_bug', 'against_rock', 'against_ghost', 'against_dragon',
                   'against_dark', 'against_steel', 'against_fairy'])
x.head()

name  generation  status  ... sp_defense  speed base_experience
0      Bulbasaur           1  Normal  ...         65     45            64.0
1        Ivysaur           1  Normal  ...         80     60           142.0
2       Venusaur           1  Normal  ...        100     80           236.0
3  Mega Venusaur           1  Normal  ...        120     80           281.0
4     Charmander           1  Normal  ...         50     65            62.0

[5 rows x 15 columns]

In [446]:
# Preparing the data 
X=x.drop(columns=['name','type_1', 'type_2', 'species', 'status' ])
y=x['speed']


In [447]:
X.head()

generation  type_number  total_points  ...  sp_defense  speed  base_experience
0           1            2           318  ...          65     45             64.0
1           1            2           405  ...          80     60            142.0
2           1            2           525  ...         100     80            236.0
3           1            2           625  ...         120     80            281.0
4           1            1           309  ...          50     65             62.0

[5 rows x 10 columns]

In [448]:
y

0        45
1        60
2        80
3        80
4        65
       ... 
1023    138
1024    128
1025    138
1026    130
1027    130
Name: speed, Length: 1028, dtype: int64

In [449]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [450]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [451]:
y_pred = classifier.predict(X_test)

In [452]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

df

Actual  Predicted
907      36         36
680      44         44
240      30         30
991      70         70
538      66         66
..      ...        ...
951      57         57
429     100        100
19      145        135
239      91         91
247      45         45

[206 rows x 2 columns]

In [453]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))


[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 4 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]


In [454]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           5       0.00      0.00      0.00         1
          10       0.00      0.00      0.00         0
          15       1.00      1.00      1.00         4
          20       1.00      1.00      1.00         5
          23       1.00      1.00      1.00         1
          25       1.00      1.00      1.00         3
          29       1.00      1.00      1.00         1
          30       1.00      1.00      1.00         6
          35       1.00      1.00      1.00         3
          36       1.00      1.00      1.00         1
          37       1.00      1.00      1.00         1
          40       1.00      1.00      1.00         9
          42       1.00      1.00      1.00         1
          43       1.00      1.00      1.00         1
          44       1.00      1.00      1.00         1
          45       1.00      1.00      1.00        12
          46       1.00      1.00      1.00         2
          48       0.50    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [455]:
#accuracy score
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Accuracy: 0.912621359223301
